image: alpine/edge

packages:
  - cmake
  - gperf
  - perl

sources:
  - https://git.sr.ht/~rcr/rirc

tasks:
  - setup: |
      cd rirc
      git submodule init
      git submodule update --recursive
      export MAKEFLAGS='-j $(nproc)'
  - build: |
      cd rirc
      make clean
      make all
      make check

triggers:
  - action: email
    condition: failure
    to: mail+sourcehut+builds@rcr.io
