image: alpine/edge

packages:
  - cmake
  - gperf
  - perl

sources:
  - https://git.sr.ht/~rcr/rirc

tasks:
  - setup: |
      cd rirc
      git submodule init
      git submodule update --recursive
  - build: |
      cd rirc
      make clean
      make -j2 rirc rirc.debug test

triggers:
  - action: email
    condition: failure
    to: mail+sourcehut+builds@rcr.io
